-- Usuario 1: dueño
CREATE USER PRY2205_USER1
IDENTIFIED BY pry2205_user1
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- Usuario 2: consultas
CREATE USER PRY2205_USER2
IDENTIFIED BY pry2205_user2
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

--Modificaciones de permisos y roles

GRANT CREATE SESSION TO PRY2205_USER1;
GRANT CREATE SESSION TO PRY2205_USER2;

CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_P;

GRANT CREATE TABLE TO PRY2205_ROL_D;
GRANT CREATE VIEW TO PRY2205_ROL_D;
GRANT CREATE INDEX TO PRY2205_ROL_D;
GRANT CREATE SYNONYM TO PRY2205_ROL_D;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_ROL_D;


GRANT CREATE TABLE TO PRY2205_ROL_P;
GRANT CREATE SEQUENCE TO PRY2205_ROL_P;
GRANT CREATE TRIGGER TO PRY2205_ROL_P;


GRANT PRY2205_ROL_D TO PRY2205_USER1;
GRANT PRY2205_ROL_P TO PRY2205_USER2;


CREATE TABLE CLIENTE (
  ID_CLIENTE NUMBER PRIMARY KEY,
  NOMBRE     VARCHAR2(100)
);


GRANT SELECT ON CLIENTE TO PRY2205_USER2;

CREATE PUBLIC SYNONYM CLIENTE FOR PRY2205_USER1.CLIENTE;

SELECT * FROM CLIENTE;


--Verificación rápida:

SELECT * FROM CLIENTE;           -- OK
SELECT * FROM PRY2205_USER1.CLIENTE; -- Puede fallar (si no hay grant directo)
